name: Node.js CI and Playwright Tests
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

on:
  workflow_dispatch:
  schedule:
    # Test 3 times a day
    - cron: '0 */8 * * *'

jobs:
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image
        image: mysql:latest
        env:
          DB_NAME: 'library'
          DB_USER: 'root'
          DB_PASS: ${{ secrets.DB_PASS }}
        #
        ports:
          # Opens tcp port 3306 on the host and service container
          - 3306:3306
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Connect to mySQL
      # Runs a script that creates a mySQL table, populates
      # the table with data, and then retrieves the data
        run: echo "Connected to mySQL"
      # Environment variables used by the script to create
      # a new mySQL table.
        env:
          DB_NAME: 'library'
          DB_USER: 'root'
          DB_PASS: 123456
          # The hostname used to communicate with the mySQL service container
          DB_HOST: 127.0.0.1
          # The default mySQL port
          DB_PORT: 3306

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.21.3']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:      
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies of back-end and start building and running
        working-directory: source/back-end
        run: |
          npm install
          npm run start &
      - name: Install dependencies of front-end and start building and running
        working-directory: source/front-end
        run: |
          npm install 
          npm run serve &
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install pytest-playwright
          pip install -r requirements.txt
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: Run your tests
        run: python -m pytest

