# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "origin" ]
  pull_request:
    branches: [ "origin" ]
  schedule:
    # Test 3 times a day
    - cron: '0 */8 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.21.3']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies of back-end and start building and running
      working-directory: ./back-end
      run: |
        npm install
        npm run start
    - name: Install dependencies of front-end and start building and running
      working-directory: ./front-end
        npm install 
        npm run serve
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
    
